pipeline{
    agent any
    tools 'maven_3_5_0'
    stages{
        stage('BUILD MAVEN')
        steps{
            checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/sushilkumar320/Devops-automation-java']])
             sh 'cd /home/ubuntu/Devops-automation-java && mvn clean package'
        }
    }
    
    
}