pipeline {
    agent any
    tools {
        maven 'maven_3_5_0'
    }
    stages{
        stage ('BUILT MAVEN'){
            steps{
             checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/sushilkumar320/Devops-automation-java']])
             sh 'mvn clean install'
            }
       }
    
    }
}








